Updating.

diff --git a/.cicd/Jenkinsfile.coastal b/.cicd/Jenkinsfile.coastal
--- a/.cicd/Jenkinsfile.coastal
+++ b/.cicd/Jenkinsfile.coastal
@@ -70,6 +70,13 @@ def generateStage(nodeLabel) {
          
                           echo "Testing concluded...removing labels for $machine from $GIT_URL"
                           curl --silent -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${GITHUB_TOKEN}"  https://api.github.com/repos/${GIT_OWNER}/${GIT_REPO_NAME}/issues/${CHANGE_ID}/labels/$machine-RT
+
+                          RESULTS=`grep 'Result:' logs/RegressionTests_$ufs_machine.log | awk '{print $2}'` 
+                             if [[ $RESULTS == "FAILURE" ]] ; then
+                                echo "Regression tests failed on ${NODE_NAME}!"
+                                exit 1
+
+                            fi
                        '''
                     }
                     else {
